server:
  port: 9001
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: clienteweb

#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

feign:
  hystrix:
    enabled: false
